# Site settings
title: Kota Ide
email: ir4van@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tempat dimana ide-ide hidup dan memberi harapan untuk masa depan yang lebih baik.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kotaide.com" # the base hostname & protocol for your site
twitter_username: ir4van
github_username:  navri

# Build settings
markdown: kramdown
