# Site settings
title: Irvan Yusirman
email: ir4van@gmail.com
description: This my personal site than can i share in public. This personal site develop using Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://navri.github.io" # the base hostname & protocol for your site
twitter_username: ir4van
github_username:  navri

# Build settings
markdown: kramdown
