# Site settings
title: Irvan Yusirman
email: ir4van@gmail.com
description: "Ini adalah situs pribadi saya yang dikembangkan dengam aplikasi Jekyll."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://navri.github.io" # the base hostname & protocol for your site
twitter_username: ir4van
github_username:  navri

# Build settings
markdown: kramdown
port: 4002